- name: Create credentials file update-gcloud-firewall
  template:
    src: "{{ gcloud_credentials_update_firewall_filename }}.j2"
    dest: "{{ secrets_folder }}/{{ gcloud_credentials_update_firewall_filename }}"
