app_name: update-gcloud-firewall
app_folder: "{{ jobs_folder }}/{{ app_name }}"
docker_image: "smurfpandey/{{ app_name }}:latest"

# Variables required by update-gcloud-firewall service
gcloud_credentials_filename: gcloud-update-firewall.json
gcloud_credentials: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63646438623935643634393336613735626234313232306265646162643735303030636336313061
          3636363961643538326230646337363932363833643734660a316431663430343336663235653335
          33393438616630323661313736383730376264386530666465346564613563626534393636666234
          3532663034393864300a396537386134346433326636323964323666623630346536663061303262
          37346363343735663930386565626264366137633034323936653865343833656263653237646232
          63353730623130373433303730383331373364633364663538333636313334653632303061663438
          62333866636538646266643062333366376261356539373134343633646339653130386235666636
          36356135656262613131303932646138623262316430356237373565306565663637356531346330
          66363537636162386531323630633731316265373731363438613936353635323562613264343762
          66623636633961636634656164653539303133343531646331343731616563346364656636636262
          63633564373435373934393833373430313530323363643138383864386162326339306333346430
          66366564633339666533636333383333633361306261633436303266653338356566656435646530
          62373637663338353339346334653861333964336638353536363864663634373536643837306535
          36353539366532626662336363376263613763343838656130643461363537333433313734323665
          63326337353534333264353866663630646335616264643261636461353066616664653639623531
          64643532373461636431326534366634386366306363646662646535623332376461653865666364
          64363365373433663731613861343536666539373830333464383766353831653633313434313237
          65316434623565333135643336326632366630353936323362396538646537656639643937343433
          64356638666566303363636633353162363333663763643530356561383835353664373437313630
          36303462383232666165633632646632636439623666383939316630333361373065383039333535
          35303766303361363166626437636436383965623963306261393733316236663532353537376231
          37653932346537656438616137363639633930313265393066366435313264373735633633633836
          62373366383334373264353937343762303861636635646265643061613639356632353731383038
          63393438373235663033396136316235663066393934663133616539313838613730616162623733
          61356135376536396263656666656463336463366639636231646334393664323934646231653337
          34653463633633323737373932333335333030393032346163303038386332333937656466306137
          37333134353938616233346636366135336666323432346164346562323232363034333834616130
          65343164333937303139376531613930373531383239343563653932656232343566653861393065
          61316334353035633934396532666136366235323364623938376233303135323634623366393466
          37396436643637333932316235616138303532383264623235336464336365663030373438306634
          63323331386331393638373231316366613931346335303733636562653931376361346537333538
          32633766366131396638303534336535303134363437356539396263386563386630663265666164
          31396663616636653931636433613037643764643331363737643834343961326263333237306263
          61333332343633656233326262373035386234323138643534363438323432653936636637663939
          35373930663836323366306261326431346564363435356132643166633362363766636136346531
          62303831613363626231366631336261363035353530616438313437626466343336333663366532
          37646261343632613635393536336164616161373162626564623132613834386639326664366536
          66306263306163663939616237343235613961613934663536343864393965373633393566373962
          61656433383165333430646464376537356436663665626230636331616532383266633337613265
          39636562663663633933633835353930363365353961363439616539386335666437303637623063
          36616236653435326334326239373131636238666362386636323062613439316134353262386662
          31313433356362656264653735326336646631653333343264313635643635646463656136343463
          64633638666435636134653061623963613233653338666437323134623835386233633530323536
          33663163303235313961376164316430623862616138643836616231313138346631333537663735
          65633136373337393330613961343362333038356464633430366563633634663864343262363666
          35616463353165343065376561353830656562326532316135666530613564353065303431383039
          62623631643038656137323264373731643236326632623933336637646537363330323262373737
          39356333306134376430653131636636663362636135326535383663643337623334646635633434
          64383137376133613639656635613934333537623532386230396631326534303233383036336437
          63623930323436656132643733353338353430623533323336316338363132623265346265313930
          33333531613062353436653932393366366662663132323639333464623031636263323238613362
          61303032393234393638363938323430376262626338393235363163363230323537613139353465
          36313965633064353234386332323664626362666331316163386133326636613964323533306632
          35383265356537333061336465353738336166393730666465643565353061353236653132306638
          64373461383164303835616238323666303833333864363866323933343337626665323634636431
          35343838313864363964613739333330626536316563316532313136343330353337363135643233
          62643833303731636536656366306365633865393837666233313530326638326362633465643338
          31373931363733636636633266643834643337353336613538346332396562313638623239646534
          38333262393636373232353839363264376138653432313831623261343636376537326237316466
          30383731663236353431653631356635333630653031306262633965306264383635613633636136
          34656230393964346631353037383635336366333964643133653465656139373262663232373664
          38613964376233636562656464353165343263616562383235366663333731353631326430623466
          35633334616134396335643938663862343932626563343133373764636439376339343234653665
          30323233353234623639323035653066343834613563623334336436343434303666303666663935
          61346639653333333838346231663364666164383232353635383632323236656438656264653030
          64386133633261376130613734333965383231386466376630636635376633366238316438323833
          35343166376138666433656634666134366531306630376365353636643231346631653635333033
          30653163663363306231333165326638646339393064613261306266653539343235313838613764
          62666564303932396366633165313239656463626131623065653562326635353539333632656363
          63653162623434333536313137663735623936383137323661313439393931633734316432353561
          63396137373939623333313032613363363761303130396130313065626634333335326161646533
          34626163303262626364363362616134393435633765623064343231633762383363356339356166
          65363834653666623664326566323339333837613163343335366432656435666262626366316562
          63313032663630623830613939323837396262343161383530643137363433313938333238356435
          64613639623835346666336533323532386466633061643962663039643263626135373333336238
          61636362366339346434613733303139616439393536333534656234326563343365383362616161
          65323732343739376464613933346366353366353832356637343134383864306633663536393136
          36616637383631363436323263316661613566376237623135646362313635376539333366643361
          63643535656535373466316262653362663636303036343739326132656133306433393537376234
          63376631633331313339373932363036366333646332333764383531313765343265653135653836
          66353565386565663934386639333339313863393437613239646238323935343662616434313336
          62303261386261393632393563396132643232653061373633333831613665336634663435383633
          33646339636566643230626162333536663164333165353366623064663233336636313732663830
          30326264386330353566303132623636393233303538373931316163353566313437346462393634
          63326435336132383138616264636332313835353334346163666237643562396230343662646234
          36353437653737636661646232393065616638333834343237313162333433326665653537643864
          64306534343863323538643130656631623166386161336337353236346464393531353161323465
          33303438336530313739383066613235343837326166383731666266323237656265613161613633
          38353166333131356663333539636437653436623535633766663661363166646639333332633366
          32323863306239383235633566666635376664373333636431353061623965616637633039383735
          64613932333733363734306635653239396165363835623636663839333239626331346437626639
          38336131396237353664613031373361373232353338313563643431626534613462366562636638
          37633065623565316639353432396638653065343035323830373565363734653630653465363238
          37616336306238313733333062643738633762393636633337323235306536633031616237633030
          32653666356538353636663330396232383830313732623364383234616330643164346130306162
          36666466323236363364633438376338313561343161636163356335373832646164333536376633
          35353864383761353565336363616635323638333137653433663263333039346239623164653662
          38366230323761353761623438653766323264313338643330343939623361323131306361313731
          64643931623033346339313733396337623966646465663464613263633032313338313833326162
          61316338333462373133363062353261393238373136656533663666373939653534326236333833
          66326634613263613435643239346665656566303437376664363635353966656463623030643830
          62373137353133616337353134643562646365353139396531323230396564313933356634383937
          34363964303531373534386162323938383735373638333463656136626565363664666133626363
          62366437643962613534666331666665336538313965386163633038306435336531346166663436
          61323731623065653364363863346462623062333033373435373130376436323662666638333464
          37346538376165373231393031303730613761303638656236653832363732336364363833353361
          37636130353635623435373066613831383966646233663465663632393039303830613235353634
          32313836316536343738353063386336393539623162633934323062626438383463316363633330
          37373962333535316462326231366233303538313239313034313234303835313835356465313561
          32333232333438376464346161396134316638333637373738323239376639663931373530396332
          31356661656261333566396330656334396439346164336463386638656530396535303435333932
          36316233333138616632313066623666343962346139346332386130343231623735363165643061
          65326462393865643533373738633766633839346364333761333566373438303261343165386633
          38313636356136643439303835356637666165373933613734663365306661356165663438656130
          65386638373836636361373630333536326164393636376639643564353733343735343165306435
          38393839383939393631613739636436626463393832393537623937623866646131343632383331
          31343965326331396136313738333062643933653631343965336238346431396466313262626233
          30303230613135633534336239663463303639346161386564356335396437393666326565313566
          37373936643537613435643438336561343136303035363031386232643666643933663131323161
          63333061383231333862636333653964366662313432316164336237313434396237623236353366
          3735
