---

telegraf_influxdata_base_url: "https://repos.influxdata.com"
telegraf_binary_path: /usr/bin/telegraf
telegraf_configuration_dir: /etc/telegraf
influx_telegraf_auth_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65316563363466333533313761343762363131333736353734343665643435623330633263656238
          3335643632643130653839363465613735663731623166360a313231373339666434613733643434
          62653966623162343062336230333738643834623361613834616262376531613861383839383932
          3264656136666230310a336163396132366335383539643635363263336464393066623130373237
          35373334363539316437313965626231373035623662323164653337323032343636