---

chitragupta_app_directory: '{{ app_root }}/chitragupta'
chitragupta_image_name: 'ghcr.io/smurfpandey/chitragupta'
chitragupta_image_tag: 'b2172242'
chitragupta_service_name: 'chitragupta'
chitragupta_database_name: 'chitragupta'
chitragupta_database_user: 'chitragupta'
chitragupta_app_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34616639663334356639636334636666346461343335643062333564316634353966636537616237
          3430306231333132633335663531626262356364303663330a356564363764653835383566353863
          31343130393734323335343633656563373435386263363664626430323738316433643430613064
          6331353839313431340a386637623666623439393033323462316166323965303965353734393131
          61393337636264386430633265336634666638306334626263613333643637383630
chitragupta_database_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37363034353463636538366532346139383034616533373530313933666538653939613664303765
          6231393362376362653230313362616533363165656363640a306266313433363839303134616537
          35326631313736663761343130653364646537383536386531383664656234323261346535393336
          3261646363323935620a303033643661383038616533653063646139393639393264663365323134
          3235