---

transmission_app_directory: '{{ app_root }}/transmission'
transmission_data_directory: '{{ data_root }}/transmission'
transmission_image_name: 'linuxserver/transmission'
transmission_image_tag: 'arm32v7-3.00-r6-ls146'
transmission_service_name: 'transmission'
transmission_hdd_download_root: /mnt/mediahub/data/torrents
transmission_container_download_root: /data/torrents
transmission_config_enable_watch_dir: "false"
transmission_config_downloads_dir: "{{ transmission_container_download_root }}/completed"
transmission_config_incomplete_dir: "{{ transmission_container_download_root }}/incomplete"
