app_folder: "{{ jobs_folder }}/image-desc-bot"
gcloud_credentials_filename: gcloud-imagedescbot.json
gcloud_credentials: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66343266356565323364626464623766383835356634636433663239623261383736373235333530
  3363343034313539643665633339373737346339353865630a343832356535336566623561363962
  61333766363565626231646439613135316137643965663932633537633533366564356635663333
  3833353563363436610a366662623665656232343436646131666636393562353632316635653130
  65626165376230613535373237623037356535313834343465383530396135613238306633353862
  66633535373562373333323135326466623833353837363532306661633262636564356131366239
  37623032643239316330643939383461303532643831313233653536663434323363366665626137
  38383765333936316536663739623063383564643634343065663362656230643639333064346433
  37646639653538633430633937623662616366306434633566386131336434363538313964646539
  62663666636664613434363864613665386230353034346434343761313362313236306266383762
  39663932376533623064656131623263336266613138306162366566333062626435373636323835
  61333235386363393237356330656433313362306638336231313365313166353763653964633932
  30663562363136363565386535346139383161643631356666613831633562303837323063646233
  63306364626362366236636666623633373561333636653563376334636164393262663230323263
  30333531346333303236656231623931616464326136313832656130626438393732303865663938
  64376465383363353466616564396338663164376132376464306239356561626431626432646135
  31616563366230336430376233656666346639373038663431313365366535333439663961623134
  37363735333133336637326465633364643365306630363430643435663734383564666235393662
  66383332386465653838376364383435353130653266343938616437656166646632393037343736
  65323935313933633039323635663132383838303830353534623763386165363633646132396363
  32356335313736353838653731666464616464366331653166306538646561613238336636313232
  66333135656534343936353136336162363030343330626664613336353861663934363635636438
  61316166626535663930383965306635323366393534643933626466333530333934613734636139
  61363731663135353333636131663239636162303836346362353834626133383533653762396564
  66363566636139353166653433366538643633326337393736663532313231623235313737653630
  61343030636431353966363931663462363861363663333664343266313566333164613133346639
  32313963343130613265373338396438346261306438363765336331363162633663343263626635
  39303739323433626436633838383664363233396166623766643864656536333538623137353033
  63313739326163343866306563333465313562313636333530386564653433646266393936363165
  34623661643062333839653931383734336234396362366564373031366336363633626539366466
  32343965653031656334353834356133656636376236356434636434613561306264383761626436
  66366438653266653935363139356436653436376162613166396531306636653834396663393531
  61636535643532336664303232363935343030303366653164653236663834326636363033306431
  33376234666262646339613037363639353935396133323462643562633266343931623739623561
  66616332323539653961613534633339356665633237303538333237303739333265663836633563
  33656338313238646161373336666138366437366264633931666263613131633430313231363935
  61636330643365383732616664613138346630396638643432643536613264393361303136643166
  38643539366235303764353639623835363466383931396563323938323130363737646466343539
  66663161633365396539646661663735373362623761643339353935343661363766356439343238
  37316664326231343130393761346266666534356130313630346439363133626437386262373464
  39353030343339613731336462306230666131333931373764643961396661366535356664306333
  31393637393561373232356236383434346663646361323161393132663034656435373230323732
  33643565363135653136306565613334613333623935663362663634373938333036323761313063
  31633533393262363137356163313234303539653933323132613734353932336639363563353366
  61666336313866313237636463666566386333373433653164326430373837336333316130643264
  31356261313466633039396539333337623632623564643836303334366464363733373031343664
  32353435343139616239656632653835663839646431376432666437623464633434393463363838
  62313765353938323261356136323162656235623130363165383965383631643439626235313461
  63363132326435663761396561323665623838336535333362366437353162666261346263326338
  37313366313435376662363331633632636563653737633436363462343438363764363935353132
  61353032656562313161326630353938613038303432306136363432656464613061333063306166
  32383137313831343932393330323931336662356537373765623032613662323265363365646234
  64643735343363383963616334626632353632626237343430326131336537353733633463303330
  31306363393630383139616434633237613261666530366361363737633435343931333130323334
  65373634396465663735343632346633643261363263303666303363396430373165613762366133
  62336566306161653361633239636164373438643364353335396666323831333630303937623235
  35373966626430643933653761393664336632616363383166623363336431373739353239646139
  39313231656162343639613633633934633363353666323832666534653530313335326238356231
  66643439303264333339316235303964336162383634323634343662636565626437323931666437
  62323534313236353533343735373161326432613136643735666238653864363965613736643338
  34373332333839633961383334313134613430333961633334636466323636333734333930373266
  66316364613165616264326464333337623135346536313039626131613561333863333265333536
  31646338643565613364633138646662326230316535643534386635306239666233373561376339
  63333561626633613763626335346135366364376435323039613531323131313763323034393363
  62343361313635613965356438343163316563303163313466616264386638336162306262386437
  33333031646139313763663432646564353133383834343565306139303733623136393363613631
  66373533613862363435313864323337653638326633326530313634373633303763653531663564
  64383930396262336338366433343137633864343736326565306238323831323666313165316337
  33616539363565323939376265396265353034393438393834353931623537663138653736306339
  66623865616261336662316662623764353563363064343165616233373365313563613137623461
  35643230626262373931353436316638663738663834313466323163663139356561346630623732
  36393936393139336132623665666561376564313863646634373735306132616332616335653763
  30326661343936353366326463353466366331386261373664333665316562336138653233636664
  36373337303863636263316330376666323361366337653563316266316461646633336663353736
  63646261623835353335623936613935346531633165333838656632653164306365663739623830
  39363938343536663437663637623437346463653136333030353031353436643930643462653033
  39666433373962366230633161626262303833656566336263616662666161306163356531616439
  39643161346235306337393030343230663666323037643861613464313033663366313538316634
  37656265633237663261343735366434656134393032376566373866666234333234616432393737
  31326236653432363834333735643233313038343762333066643338343036393233333662386434
  61396138343831613432383766643333623261396362633562643365393334316536326335386164
  38313536373739636132393366633734303062643539316138666131633461616232313931336131
  66663138366137653263343439646632653966653436383561373463616537633539366238336237
  61663966393033313735326639646562663536303037373864616339353236336436376631643735
  37313366666565663135333632656336343732326139613866616639666165353637663434353636
  33646436333331346461366235633530393338396633363830346465383166376363643931333165
  39636430323937313632356434333633396135313531393666653635393039633565366437646161
  33663666336161376532313634653936353961323636656137326164383566303431616531616166
  61623361393634356164666333396136396236653038383433323036613637336239306230373030
  63636662623733643466623733323063383236313664643638656637343939333930653730346162
  33333366316139306364666235363761643132636239623531633266306161623138623832356131
  31393733343335663565383632383934633264376539383438373335376230313961386638663133
  64326639383765396138633336383836633838333930313561643964643834326564346264353033
  31663837326230326261326435656462363230306665633963623333343530353030643565613964
  38316664303739306134356335633839343439613833623135383237323337313233343839326366
  35383437386164383830316163633137366131613237343733633738313237313464383438613934
  62313932373330343336623664363231376163333136313139366531306136313335636536393930
  39333030373863396466326165393863666236366334396566636664313338383161346639623035
  32316563663935616436373861663166616139356331373762653263343966633536353536623736
  65613966373764326539363866316138396563363433613661383535373339663031333736396434
  65376139623732383361656334396262666130663732613836386366363764346133383363643266
  35633638353531666265633161613564626339346436336564663764306335626364373630366366
  34366435336435346364336166393461316330613930613233343666616530303332303631633063
  36353734306334303835636362646565623438303363386330616664323234383864613339653331
  39303232363833613563383466643064623534326264663339613730656439353330373933306339
  39343361653736656165623165623164653838366136336236656131363834356166343733366433
  63646537356264623738333765336238363064626561636532656638353964373066653035373464
  61643463663739303737366239653733333433643462613034633132646532666635353236333737
  32376631646332623833613763623437626438356239306662623063643864666331363336303361
  36306265646632633839656632303266653838666533343439303666386633396364303532323362
  34633939346563666335646330356230613265366135616164656339376466303461333037306635
  37653066343765343462646661383137386231353365313162386562323465303535373862636363
  66306164306237356139363032653639306563383666356565646165613038396238393837306436
  61336233613637636133316430636334636638343464343062613265313739373031386636333536
  35636561316465633463353330646139613431663235366366613735303930613462623439343735
  63643566663030633033636534316333303634393139626437323661626532343035613536393663
  35653837306130333632393765383834383262343036623236616438656334616532383039666666
  35636334316135393935393365386334346532656364616639326337653732636363396439373037
  33343431343764393566316462353063666563353236623330303137393036366434363661376235
  62323239613839323930666161306337656637326130326630613334633264306137376634666636
  3230
