---

wireguard_app_directory: '{{ app_root }}/wireguard'
wireguard_config_directory: '{{ wireguard_app_directory }}/config'
wireguard_image_tag: 'linuxserver/wireguard:1.0.20210914-alpine'
wireguard_service_name: 'wireguard'
