
pihole_app_directory: '{{ app_root }}/pihole'
pihole_data_directory: '{{ pihole_app_directory }}/data'
pihole_appdata_directory: '{{ pihole_data_directory }}/app'
pihole_dnsmasq_data_directory: '{{ pihole_data_directory }}/dnsmasq'
pihole_image_tag: 'pihole/pihole:v5.1.2-stretch'
pihole_service_name: 'pihole'
pihole_ui_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34353762376463343132626365326361333365353561666236313864386163316235656635356630
          3361316230326137373232623538363563376162653430300a666439366662643263376533613664
          36626164313263303863323963346337373939386637316138376137643566656439623539623630
          6432386462663735340a353862656132383139656461343934353762626633626133666462613139
          38653837373930363732616434316132343134376466366464373464623330353265
