
postgres_app_directory: '{{ app_root }}/postgres'
postgres_scripts_directory: '{{ postgres_app_directory }}/scripts'
postgres_backup_directory: '{{ data_root }}/postgres/backup'
postgres_image_tag: 'postgres:12.4'
postgres_service_name: 'postgres'
postgres_admin_user: 'admin'
postgres_expose_on_host: false
postgres_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66353338363463363964353339666662363061333032633438663562343933383263333239613362
          6233663330653037323336393638643763326539396331620a363135366439646339356435626139
          31623830366430376262383633393961353131653230646366313961353635323463663264323132
          6136333836363238370a623230383730373330646531316236623431363862643432363835383762
          30626166316134633739343435633637383036326432623534323533313730613035
postgres_backup_healthcheck: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323438306634623165353962356434663234326366383262303733366538323339323261616435
          3463616536643262303364346638313962343063303235640a616134376435346665613537383864
          30356564636630626533623830333837343662373534626661303866333862353131333466626166
          6639323063313635300a643837336232316461633663353262636130313630323265383439306663
          35383132396636386562363732336263353534663435656531363465613261393230313735306335
          66336564313162653464366230363962343739643663303531643037313731653763303066353863
          376463633431303565323836323064653863
