---

uptime_kuma_app_directory: '{{ app_root }}/uptime-kuma'
uptime_kuma_data_directory: '{{ data_root }}/uptime-kuma'
uptime_kuma_image_name: 'louislam/uptime-kuma'
uptime_kuma_image_tag: '1.17.1-debian'
uptime_kuma_service_name: 'uptime-kuma'
