# Variables required by ImageDescBot service
idb_healthcheck_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62633235353935366630346636393964333936636639363732666231376539393665613661623362
  3564613632313163323664656436613533313861663435650a643839376265313739323631633438
  35333534346561626362636233616434386533333335323034383336623461333633616561303130
  6666353964323338350a646137363264643839373234363434366635633364633466326564663561
  65363539303435623864616661656230336333393035396130646265303262623930363762643039
  63663130346364633161323432306464653435393166313862386363343536656435626337653662
  376132323930353865613063336363663235
idb_twitter_consumer_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35313061656131313130653330323861613661366564636238326666356466353166653432383164
  3934393137366161343634363636623761646161373966300a333132633930323533613765366230
  35303032353538653465363937336630303061333631613934643238333437633335313861326534
  6331623565363864380a633735333666653762323665353338373235633834623932346136616331
  63666332336137376664613362653232303765383366653034663462356362303064
idb_twitter_consumer_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66373930636462303765663738623438386538343263643536303237346166623036636131383232
  6338343164623565393263363566393836306630343935660a613336386563626464373261383436
  34333639633264653162653333636639363736326566396661653034633433306233366464323232
  3431373032376162370a376539323438363234633562626561353539653230363564393266363461
  39316266363265323038313362333864653632643039393538396531326361633163363636643266
  63366262386365633231306335633862323464383364333663646439633664343133626232393565
  633739623864656661333362666263333032
idb_twitter_access_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34346131363061323861363362353232633162633931316131323639663337363832323736306331
  3930363636396563363532663739633538633366366236350a373531343232333964623433376333
  31626133653333623633363137303633313131333338303539663937666333343663623130653664
  3133353038626432370a623639323336396132333733393939373736363939366163653032346437
  35346438646638626265333664613031303361383431646565393237376533336564316136336430
  38623534303035633337316238316361306537613239633033373334303636393662623030363634
  333838326530616365303737306332323363
idb_twitter_access_token_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38633061383566363532623964323133323336343962393562376330646562393330336133396431
  6531646361623836323163393130376231316461633539650a343034663733646532643364376130
  37643965346437643264653031373839346139313762376534366131613835393965316439316662
  6632316636303630650a323839653332626232316535666464366537363730346233653831323436
  34363237363730323461333734623234366565613435376132613939393735323135643239666261
  3266636332376366326464376537653132653964346261643039
idb_google_application_credentials: /keys/google_cloud_keys.json
idb_microsoft_computer_vision_API_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64373131393266383533376130363461326362613766306433343466383039326434633261343635
  6433376639303262366630623361633339643137343934640a343732373732333331656431663030
  38343939373263376534363239336437323039613432313535316234343433623735303766613662
  3231366437663263350a633930653639663933323338323833316665646230633837333331323338
  66653038343361636535353666663564343932383138383466343031356661346163333661326561
  3730333531613833616261353033613866623863636232643030
idb_microsoft_computer_vision_API_ENDPOINT: https://centralindia.api.cognitive.microsoft.com/
idb_aws_access_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38643663386166346335313037633134386165656265623331646666353535653638653134613361
  6531633930623730393834333730643732376665646633360a333939313062343030363130306463
  38323539666636613265613234313265616435383163636334636537353237396630316433363330
  3430376137393936610a323730373738333336376332343464336364663864323734666166326461
  36386531643265613832373639393838396138626631303363336435353134306334
idb_aws_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62653235383933613561663363373336353934633239393637366665323831653630313261306235
  3161666566343534313536663334613734363235393966390a623765656365363662313637303963
  35636661396265356166333536626164333135363432373864333162396637323537316662626534
  3239336436643730390a663163663261326535333664366338663264306561366232646562623531
  63663366633161623038303439653532636438356262653439306133363430616637303032623132
  6638653035353265366161613366643262336335656433613361
idb_sentry_dsn: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62393536373138356137303539666133393635376130613434613565646264653433663831373038
  6232323732613339363866303935313030333635323839620a313738653331343536343532386134
  37643666366665663233643066383164396565323137383933343666386337613331396666353536
  6132633061633062620a626134383038306330326135343765363838313333303262306464383461
  32656364376164306530376665353439613834373334333534666364346632356532303061343730
  65623031386336393535333232373666373162623434383538373162353239666531306266663636
  626365393563326534363761626466643737
