---

traefik_app_directory: '{{ app_root }}/traefik'
traefik_data_directory: '{{ traefik_app_directory }}/data'
traefik_acme_directory: '{{ traefik_app_directory }}/letsencrypt'
traefik_image_name: 'arm64v8/traefik'
traefik_image_tag: '3.0'
traefik_service_name: 'traefik'

cloudflare_api_email: "{{ lookup('env','cloudflare_api_email') }}"
cloudflare_api_key: "{{ lookup('env','cloudflare_api_key') }}"
