google_application_credentials: /keys/google_cloud_keys.json
healthcheck_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36623335626539363735653938303732633065663862643764303731316161663465383033363937
  3364616565363863383762626436636637333164376261300a326132343037383436623363313638
  32313964353039333834343261613232643566323735353965343536663062623364343063633062
  6133613135393566350a373536303162393936336263326136356531366239623962356132363237
  62663764353965393565653866393434656537396666666637613533653432633635626234383437
  34363366336233396137323237626431373931633131393266313433613363343465353762653265
  663331303035353934353937333938363836
